"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowRight, Check, Info, MapPin } from "lucide-react";

const services = ["Däckbyte", "Omläggning", "Balansering", "Punktering", "Ventilbyte", "Däckhjälp"];
type Booking = { service:string; registration:string; date:string; time:string; address:string; postcode:string; name:string; email:string; phone:string; notes:string };

export default function BookingFlow({ initialService = "" }: { initialService?: string }) {
 const [step, setStep] = useState(1);
 const [booking, setBooking] = useState<Booking>({ service:services.includes(initialService) ? initialService : "", registration:"", date:"", time:"", address:"", postcode:"", name:"", email:"", phone:"", notes:"" });
 const set = (key:keyof Booking, value:string) => setBooking(b=>({...b,[key]:value}));
 const advance = (e:React.FormEvent<HTMLFormElement>) => { e.preventDefault(); setStep(s=>Math.min(s+1,4)); window.scrollTo({ top:0, behavior:"smooth" }); };
 return <div className="booking-layout container"><div className="booking-left"><p className="kicker">BOKNINGSKONCEPT / DEMO</p><h1>DÄCKSERVICE<br /><em>PÅ DITT SÄTT.</em></h1><p>Se hur en enkel bokning skulle kunna fungera på nya Alex Däckservice.</p><div className="booking-disclaimer"><Info size={20}/><span>Detta är en prototyp. Inga tider bokas, inga uppgifter sparas eller skickas.</span></div><div className="booking-decor"><div className="booking-decor-circle">AD</div><span>VAGGERYD / MOBIL SERVICE</span></div></div><div className="booking-panel"><div className="booking-progress"><span>DIN BOKNING</span><strong>{step === 4 ? "ÖVERSIKT" : `STEG ${step} AV 3`}</strong></div><div className="progress-track"><div style={{width:`${Math.min(step,3)/3*100}%`}}/></div>
 {step===1 && <form onSubmit={advance}><div className="form-head"><span>01 / TJÄNST</span><h2>Vad behöver du hjälp med?</h2><p>Välj det som stämmer bäst. Tjänsterna går att ändra innan bokningen skickas i en framtida version.</p></div><div className="service-options">{services.map(s=><label key={s} className={`service-option ${booking.service===s?"selected":""}`}><input type="radio" name="service" value={s} checked={booking.service===s} required onChange={()=>set("service",s)}/><span>{s}</span><span className="option-check">{booking.service===s ? <Check size={18}/> : <ArrowRight size={18}/>}</span></label>)}</div><button className="button button-green form-next" type="submit">Fortsätt <ArrowRight size={19}/></button></form>}
 {step===2 && <form onSubmit={advance}><div className="form-head"><span>02 / BIL & TID</span><h2>Berätta om din bil.</h2><p>Datum och tid är önskemål i den här demon. Tillgänglighet visas först efter anslutning till bokningssystemet.</p></div><div className="field-grid"><label className="field full">Registreringsnummer<input value={booking.registration} onChange={e=>set("registration",e.target.value.toUpperCase())} required maxLength={10} placeholder="ABC 123" autoComplete="off"/></label><label className="field">Önskat datum<input type="date" value={booking.date} onChange={e=>set("date",e.target.value)} required /></label><label className="field">Önskad tid<input type="time" value={booking.time} onChange={e=>set("time",e.target.value)} required /></label></div><div className="form-controls"><button className="back-button" type="button" onClick={()=>setStep(1)}><ArrowLeft size={18}/> Tillbaka</button><button className="button button-green" type="submit">Fortsätt <ArrowRight size={19}/></button></div></form>}
 {step===3 && <form onSubmit={advance}><div className="form-head"><span>03 / PLATS & KONTAKT</span><h2>Var kan vi nå dig?</h2><p>Uppgifterna används bara för att visa en lokal sammanfattning på nästa steg.</p></div><div className="field-grid"><label className="field full">Adress där du önskar service<input value={booking.address} onChange={e=>set("address",e.target.value)} required placeholder="Gatuadress" autoComplete="street-address"/></label><label className="field full">Postnummer och ort<input value={booking.postcode} onChange={e=>set("postcode",e.target.value)} required placeholder="567 00 Vaggeryd" autoComplete="postal-code"/></label><label className="field full">Ditt namn<input value={booking.name} onChange={e=>set("name",e.target.value)} required placeholder="För- och efternamn" autoComplete="name"/></label><label className="field">E-post<input type="email" value={booking.email} onChange={e=>set("email",e.target.value)} required placeholder="namn@exempel.se" autoComplete="email"/></label><label className="field">Telefon<input type="tel" value={booking.phone} onChange={e=>set("phone",e.target.value)} required placeholder="07..." autoComplete="tel"/></label><label className="field full">Övrigt (valfritt)<textarea value={booking.notes} onChange={e=>set("notes",e.target.value)} placeholder="Något mer vi behöver veta?" rows={3}/></label></div><div className="form-controls"><button className="back-button" type="button" onClick={()=>setStep(2)}><ArrowLeft size={18}/> Tillbaka</button><button className="button button-green" type="submit">Visa sammanfattning <ArrowRight size={19}/></button></div></form>}
 {step===4 && <div className="booking-summary"><div className="summary-icon"><Check size={32}/></div><span className="small-label">SÅ HÄR SKULLE DET SE UT</span><h2>Din förfrågan är klar att granska.</h2><p className="summary-warning">Det här är bara en förhandsvisning. Ingen bokning har skapats och uppgifterna har inte skickats.</p><dl><div><dt>Tjänst</dt><dd>{booking.service}</dd></div><div><dt>Bil</dt><dd>{booking.registration}</dd></div><div><dt>Önskad tid</dt><dd>{booking.date} kl. {booking.time}</dd></div><div><dt>Adress</dt><dd>{booking.address}, {booking.postcode}</dd></div><div><dt>Kontakt</dt><dd>{booking.name} · {booking.email}</dd></div>{booking.notes && <div><dt>Övrigt</dt><dd>{booking.notes}</dd></div>}</dl><button type="button" className="back-button" onClick={()=>setStep(3)}><ArrowLeft size={18}/> Ändra uppgifter</button><Link className="button button-green" href="/kontakt">Kontakta Alex via nuvarande sajt <ArrowRight size={18}/></Link></div>}
 </div></div>;
}
